package com.bureau.xerox.domain;

// Generated 19-feb-2015 5:46:04 by Hibernate Tools 3.6.0


/**
 * Log generated by hbm2java
 */
public class Log extends AbstractEntity {

    private static final long serialVersionUID = 1L;
    private String mensaje;
    private Long idProceso;
    private Long idPeriodo;

    public Log() {
    }
    
    public String getMensaje() {
        return this.mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    public Long getIdProceso() {
        return idProceso;
    }

    public void setIdProceso(Long idProceso) {
        this.idProceso = idProceso;
    }

    public Long getIdPeriodo() {
        return idPeriodo;
    }

    public void setIdPeriodo(Long idPeriodo) {
        this.idPeriodo = idPeriodo;
    }
}
