spool 03_createTable.log

CREATE TABLE FATCA.ACCIONISTAS
  (
    ID                   NUMBER (10) NOT NULL ,
    EMP_CODIGO_CLIENTE   VARCHAR2( 8 CHAR),
    EMP_TIPO_DOCUMENTO   VARCHAR2(25 CHAR),
    EMP_NRO_DOCUMENTO    VARCHAR2(25 CHAR),
    EMP_RAZON_SOCIAL     VARCHAR2(60 CHAR),
    ACC_TIPO_DOCUMENTO   VARCHAR2(25 CHAR),
    ACC_NRO_DOCUMENTO    VARCHAR2(25 CHAR),
    ACC_NOMBRE           VARCHAR2(20 CHAR),
    ACC_APELLIDO_PATERNO VARCHAR2(20 CHAR),
    ACC_APELLIDO_MATERNO VARCHAR2(20 CHAR),
    ACC_CIUDAD           VARCHAR2(60 CHAR),
    ACC_PAIS_NACIMIENTO  VARCHAR2(60 CHAR),
    ACC_DIRECCION        VARCHAR2(80 CHAR),
    ACC_DISTRITO         VARCHAR2(60 CHAR),
    ACC_DEPARTAMENTO     VARCHAR2(60 CHAR),
    ACC_CODIGO_POSTAL    VARCHAR2(20 CHAR),
    ACC_PAIS_RESIDENCIA  VARCHAR2(60 CHAR),
    ACC_NRO_ACCIONES     VARCHAR2(22 CHAR),
    ACC_PORC_ACCIONES    VARCHAR2(22 CHAR),
    ACC_PAIS_1           VARCHAR2(40 CHAR),
    ACC_TIN_1            VARCHAR2(40 CHAR),
    ACC_PAIS_2           VARCHAR2(40 CHAR),
    ACC_TIN_2            VARCHAR2(40 CHAR),
    ACC_PAIS_3           VARCHAR2(40 CHAR),
    ACC_TIN_3            VARCHAR2(40 CHAR),
    APD_TIPO_DOCUMENTO   VARCHAR2(25 CHAR),
    APD_NRO_DOCUMENTO    VARCHAR2(25 CHAR),
    APD_NOMBRE           VARCHAR2(60 CHAR),
    FECHA_RECEPCION      VARCHAR2(10 CHAR),
    FECHA_REGISTRO       VARCHAR2(10 CHAR),
    ESTADO               VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE ,
    PERIODO_ID           NUMBER (10) NOT NULL
  )  NOLOGGING TABLESPACE FATCA_DAT;
  COMMENT ON COLUMN FATCA.ACCIONISTAS.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.ACCIONISTAS.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.ACCIONISTAS.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.ACCIONISTAS.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.ACCIONISTAS.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.ACCIONISTAS.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.ACCIONISTAS ADD CONSTRAINT ACCIONISTAS_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.ACCOUNT_REPORT
  (
    ID                        NUMBER (10) NOT NULL ,
    ACCOUNT_NUMBER            VARCHAR2 (25 CHAR) ,
    ACCOUNT_HOLDER_TYPE       VARCHAR2 (10 CHAR) ,
    ACCOUNT_BALANCE_CURR_CODE VARCHAR2 (3 CHAR) ,
    ACCOUNT_BALANCE_VALUE     VARCHAR2 (22 CHAR) ,
    DOC_TYPE_INDIC            VARCHAR2 (10 CHAR) ,
    DOC_REF_ID                VARCHAR2 (200 CHAR) ,
    CORR_MESSAGE_REF_ID       VARCHAR2 (200 CHAR) ,
    CORR_DOC_REF_ID           VARCHAR2 (200 CHAR) ,
    ESTADO                    VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION          VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION      VARCHAR2 (7 CHAR) ,
    FECHA_CREACION            DATE NOT NULL ,
    FECHA_MODIFICACION        DATE ,
    REPORTING_GROUP_ID        NUMBER (10) NOT NULL ,
    PERSON_ID                 NUMBER (10) ,
    ORGANISATION_ID           NUMBER (10) ,
    PERIODO_ID                NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.ACCOUNT_NUMBER
IS
  'NUMERO DE CONTRATO O CUENTA' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.ACCOUNT_HOLDER_TYPE
IS
  'TIPO' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.ACCOUNT_BALANCE_CURR_CODE
IS
  'CODIGO DE MONEDA' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.ACCOUNT_BALANCE_VALUE
IS
  'MONTO DEL BALANCE' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.DOC_TYPE_INDIC
IS
  'IDENTIFICADOR DEL TIPO DE BLOQUE FATCA' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.DOC_REF_ID
IS
  'IDENTIFICADOR DEL BLOQUE' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.CORR_MESSAGE_REF_ID
IS
  'IDENTIFICADOR DEL MENSAJE ENVIADO ANTERIORMENTE Y SE ESTA CORRIGIENDO' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.CORR_DOC_REF_ID
IS
  'IDENTIFICADOR DEL MENSAJE ENVIADO ANTERIORMENTE Y SE ESTA CORRIGIENDO' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.ACCOUNT_REPORT ADD CONSTRAINT ACCOUNT_REPORT_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.CUENTAS
  (
    ID                        NUMBER (10) NOT NULL,
    CODIGO_GIIN               VARCHAR2 (19 CHAR),
    PAIS_BANCO                VARCHAR2 (3 CHAR) ,
    PAIS_RECEPTOR             VARCHAR2 (3 CHAR) ,
    TIPO_REPORTE              VARCHAR2 (5 CHAR) ,
    CODIGO_REFERENCIA         VARCHAR2 (5 CHAR) ,
    PERIODO_INFORMADO         VARCHAR2 (10 CHAR),
    FECHA_COMPILACION         VARCHAR2 (19 CHAR),
    ID_ENTIDAD                VARCHAR2 (5 CHAR) ,
    CODIGO_CLIENTE            VARCHAR2 (8 CHAR) ,
    TIPO_DOCUMENTO            VARCHAR2 (6 CHAR) ,
    NRO_DOCUMENTO             VARCHAR2 (16 CHAR),
    CLASIFICACION             VARCHAR2 (20 CHAR),
    TIN                       VARCHAR2 (20 CHAR),
    NOMBRE                    VARCHAR2 (60 CHAR),
    APELLIDO                  VARCHAR2 (60 CHAR),
    DIRECCION                 VARCHAR2 (60 CHAR),
    PAIS_RESIDENCIA           VARCHAR2 (3 CHAR) ,
    CIUDAD                    VARCHAR2 (60 CHAR),
    PROVINCIA                 VARCHAR2 (60 CHAR),
    CODIGO_POSTAL             VARCHAR2 (5 CHAR) ,
    REFERENCIA_DIRECCION      VARCHAR2 (60 CHAR),
    FECHA_NACIMIENTO          VARCHAR2 (10 CHAR),
    GRUPO_REPORTE             VARCHAR2 (20 CHAR),
    ID_DOC_SPEC               VARCHAR2 (25 CHAR),
    ID_REPORTE                VARCHAR2 (25 CHAR),
    NRO_CUENTA                VARCHAR2 (24 CHAR),
    TITULAR_CUENTA            VARCHAR2 (60 CHAR),
    PROPIETARIOS_SUSTANCIALES VARCHAR2 (60 CHAR),
    SALDO_CUENTA              VARCHAR2 (25 CHAR),
    SALDO_MONEDA              VARCHAR2 (3 CHAR) ,
    ENTIDAD_CONTRATO          VARCHAR2 (18 CHAR),
    VALOR_NOMINAL             VARCHAR2 (25 CHAR),
    VALOR_NOMINAL_MONEDA      VARCHAR2 (3 CHAR) ,
    VALOR_MERCADO             VARCHAR2 (25 CHAR),
    VALOR_MERCADO_MONEDA      VARCHAR2 (3 CHAR) ,
    TIPO_FONDO                VARCHAR2 (4 CHAR) ,
    MONTO_501                 VARCHAR2 (25 CHAR),
    MONTO_502                 VARCHAR2 (25 CHAR),
    MONTO_503                 VARCHAR2 (25 CHAR),
    MONTO_504                 VARCHAR2 (25 CHAR),
    MONEDA_501                VARCHAR2 (3 CHAR) ,
    MONEDA_502                VARCHAR2 (3 CHAR) ,
    MONEDA_503                VARCHAR2 (3 CHAR) ,
    MONEDA_504                VARCHAR2 (3 CHAR) ,
    ORIGEN_503                VARCHAR2 (2 CHAR) ,
    ORIGEN_502                VARCHAR2 (2 CHAR) ,
    ORIGEN_501                VARCHAR2 (2 CHAR) ,
    ORIGEN_504                VARCHAR2 (2 CHAR) ,
    CODIGO_CUSTODIO           VARCHAR2 (4 CHAR) ,
    ADMINISTRACION_MERCADO    VARCHAR2 (2 CHAR) ,
    ESTADO                    VARCHAR2 (1 CHAR) ,
    ESTADO_PROCESO            VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION          VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION      VARCHAR2 (7 CHAR) ,
    FECHA_CREACION            DATE NOT NULL ,
    FECHA_MODIFICACION        DATE ,
    PERIODO_ID                NUMBER (10) NOT NULL,
    PERIODO_PARTICION         AS (SUBSTR( TRIM(TO_CHAR(TO_NUMBER(SUBSTR(PERIODO_INFORMADO, 1, 4)) - 2014)), -LENGTH( TRIM(TO_CHAR(TO_NUMBER(SUBSTR(PERIODO_INFORMADO, 1, 4)) - 2014)) ) + 1, 1))
  ) NOLOGGING PARTITION BY LIST(PERIODO_PARTICION) (
    PARTITION PERIODO_01 VALUES( 1),
    PARTITION PERIODO_02 VALUES( 2),
    PARTITION PERIODO_03 VALUES( 3),
    PARTITION PERIODO_04 VALUES( 4),
    PARTITION PERIODO_05 VALUES( 5),
    PARTITION PERIODO_06 VALUES( 6),
    PARTITION PERIODO_07 VALUES( 7),
    PARTITION PERIODO_08 VALUES( 8),
    PARTITION PERIODO_09 VALUES( 9),
    PARTITION PERIODO_10 VALUES( 0)
  ) TABLESPACE FATCA_DAT;

CREATE INDEX IDX_CUENTAS_PERIODO ON FATCA.CUENTAS(PERIODO_ID) LOCAL (
  PARTITION PERIODO_01_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_02_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_03_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_04_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_05_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_06_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_07_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_08_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_09_IDX TABLESPACE FATCA_IDX,
  PARTITION PERIODO_10_IDX TABLESPACE FATCA_IDX
);

  COMMENT ON COLUMN FATCA.CUENTAS.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.CODIGO_GIIN
IS
  'CODIGO GIIN' ;
  COMMENT ON COLUMN FATCA.CUENTAS.PAIS_BANCO
IS
  'CODIGO DEL PAIS' ;
  COMMENT ON COLUMN FATCA.CUENTAS.PAIS_RECEPToR
IS
  'CODIGO DEL PAIS DEL DECLARANTE' ;
  COMMENT ON COLUMN FATCA.CUENTAS.TIPO_REPORTE
IS
  'TIPO REPORTE' ;
  COMMENT ON COLUMN FATCA.CUENTAS.CODIGO_REFERENCIA
IS
  'CODIGO REFERENCIA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.PERIODO_INFORMADO
IS
  'PERIODO INFORMADO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.FECHA_COMPILACION
IS
  'FECHA COMPILACION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.ID_ENTIDAD
IS
  'IDENTIFICADOR DE LA ENTIDAD' ;
  COMMENT ON COLUMN FATCA.CUENTAS.CODIGO_CLIENTE
IS
  'CODIGO CLIENTE' ;
  COMMENT ON COLUMN FATCA.CUENTAS.TIPO_DOCUMENTO
IS
  'TIPO DOCUMENTO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.NRO_DOCUMENTO
IS
  'NRO DOCUMENTO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.CLASIFICACION
IS
  'CLASIFICACION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.TIN
IS
  'TIN' ;
  COMMENT ON COLUMN FATCA.CUENTAS.NOMBRE
IS
  'NOMBRE' ;
  COMMENT ON COLUMN FATCA.CUENTAS.APELLIDO
IS
  'APELLIDO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.DIRECCION
IS
  'DIRECCION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.PAIS_RESIDENCIA
IS
  'PAIS RESIDENCIA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.CIUDAD
IS
  'CIUDAD' ;
  COMMENT ON COLUMN FATCA.CUENTAS.PROVINCIA
IS
  'PROVINCIA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.REFERENCIA_DIRECCION
IS
  'REFERENCIA DIRECCION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.FECHA_NACIMIENTO
IS
  'FECHA NACIMIENTO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.GRUPO_REPORTE
IS
  'GRUPO REPORTE' ;
  COMMENT ON COLUMN FATCA.CUENTAS.ID_DOC_SPEC
IS
  'IDENTIFICACION DEL DOCUMENTO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.ID_REPORTE
IS
  'IDENTIFICADOR DEL REPORTE' ;
  COMMENT ON COLUMN FATCA.CUENTAS.NRO_CUENTA
IS
  'NUMERO DE CUENTA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.TITULAR_CUENTA
IS
  'TITULAR CUENTA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.PROPIETARIOS_SUSTANCIALES
IS
  'PROPIETARIOS SUSTANCIALES' ;
  COMMENT ON COLUMN FATCA.CUENTAS.SALDO_CUENTA
IS
  'SALDO CUENTA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.SALDO_MONEDA
IS
  'SALDO MONEDA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.ENTIDAD_CONTRATO
IS
  'ENTIDAD CONTRATO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.VALOR_NOMINAL
IS
  'VALOR NOMINAL' ;
  COMMENT ON COLUMN FATCA.CUENTAS.VALOR_NOMINAL_MONEDA
IS
  'VALOR NOMINAL MONEDA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.VALOR_MERCADO
IS
  'VALOR MERCADO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.VALOR_MERCADO_MONEDA
IS
  'VALOR MERCADO MONEDA' ;
  COMMENT ON COLUMN FATCA.CUENTAS.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.ESTADO_PROCESO
IS
  'ESTADO DEL PROCESO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.CUENTAS.TIPO_FONDO
IS
  'TIPO FONDO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.CODIGO_CUSTODIO
IS
  'CODIGO CUSTODIO' ;
  COMMENT ON COLUMN FATCA.CUENTAS.ADMINISTRACION_MERCADO
IS
  'INFORMA SI EL CLIENTE CORRESPONDE A LA CARTERA DE ADMINISTRACION DE MERCADO' ;
  ALTER TABLE FATCA.CUENTAS ADD CONSTRAINT CUENTAS_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.FATCA
  (
    ID              NUMBER (10) NOT NULL ,
    REPORTING_FI_ID NUMBER (10) NOT NULL ,
    FATCA_OECD_ID   NUMBER (10) NOT NULL ,
    PERIODO_ID      NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.FATCA.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  ALTER TABLE FATCA.FATCA ADD CONSTRAINT FATCA_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.FATCA_OECD
  (
    ID                   NUMBER (10) NOT NULL ,
    VERSION              VARCHAR2 (5 CHAR) ,
    SENDING_COMPANY_IN   VARCHAR2 (25 CHAR) ,
    TRANSMITTING_COUNTRY VARCHAR2 (2 CHAR) ,
    RECEIVING_COUNTRY    VARCHAR2 (2 CHAR) ,
    MESSAGE_TYPE         VARCHAR2 (25 CHAR) ,
    WARNING              VARCHAR2 (250 CHAR) ,
    CONTACT              VARCHAR2 (250 CHAR) ,
    MESSAGE_REF_ID       VARCHAR2 (200 CHAR) ,
    CORRMESSAGE_REF_ID   VARCHAR2 (200 CHAR) ,
    REPORTING_PERIOD     VARCHAR2 (10 CHAR) ,
    TIMESTAMP_SEND       VARCHAR2 (25 CHAR) ,
    ESTADO               VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE ,
    PERIODO_ID           NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.FATCA_OECD.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.VERSION
IS
  'VERSION DEL FORMATO XML FATCA' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.SENDING_COMPANY_IN
IS
  'NOMBRE DE LA COMPANIA QUE ENVIA' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.TRANSMITTING_COUNTRY
IS
  'PAIS DE ORIGEN' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.RECEIVING_COUNTRY
IS
  'PAIS DE DESTINO' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.MESSAGE_TYPE
IS
  'TIPO DE MENSAJE' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.WARNING
IS
  'ADVERTENCIAS' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.CONTACT
IS
  'NOMBRE DE CONTACTO' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.MESSAGE_REF_ID
IS
  'IDENTIFICADOR DEL MENSAJE' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.CORRMESSAGE_REF_ID
IS
  'IDENTIFICADOR DEL MENSAJE ANTERIOR AL QUE HACE REFERENCIA' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.REPORTING_PERIOD
IS
  'PERIODO REPORTADO EN FORMATO YYYY-MM-DD' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.TIMESTAMP_SEND
IS
  'FECHA DE ENVIO EN FORMATO YYYY-MM-DD''T''hh:mm:ss.' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.FATCA_OECD.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.FATCA_OECD ADD CONSTRAINT FATCA_OECD_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.INTERMEDIARY
  (
    ID                 NUMBER (10) NOT NULL ,
    REPORTING_GROUP_ID NUMBER (10) NOT NULL ,
    ORGANISATION_ID    NUMBER (10) NOT NULL ,
    PERIODO_ID         NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.INTERMEDIARY.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  ALTER TABLE FATCA.INTERMEDIARY ADD CONSTRAINT INTERMEDIARY_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.LOG
  (
    ID                   NUMBER (10) NOT NULL ,
    MENSAJE              VARCHAR2 (4000 CHAR) NOT NULL ,
    ESTADO               VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE ,
    CUENTAS_ID           NUMBER (10) ,
    ACCIONISTAS_ID       NUMBER (10) ,
    PERIODO_ID           NUMBER (10) ,
    PROCESO_ID           NUMBER (10)
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.LOG.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.LOG.MENSAJE
IS
  'MENSAJE' ;
  COMMENT ON COLUMN FATCA.LOG.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.LOG.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.LOG.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.LOG.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.LOG.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.LOG ADD CONSTRAINT LOG_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.ORGANISATION
  (
    ID                   NUMBER (10) NOT NULL ,
    RES_COUNTRY_CODE     VARCHAR2 (2 CHAR) ,
    TIN                  VARCHAR2 (50 CHAR) ,
    TIN_ISSUED_BY        VARCHAR2 (2 CHAR) ,
    NAME                 VARCHAR2 (250 CHAR) ,
    NAME_TYPE            VARCHAR2 (25 CHAR) ,
    LEGAL_ADDRESS_TYPE   VARCHAR2 (10 CHAR) ,
    COUNTRY_CODE         VARCHAR2 (2 CHAR) ,
    ADDRESS_FREE         VARCHAR2 (500 CHAR) ,
    DOC_TYPE_INDIC       VARCHAR2 (10 CHAR) ,
    DOC_REF_ID           VARCHAR2 (200 CHAR) ,
    CORR_MESSAGE_REF_ID  VARCHAR2 (200 CHAR) ,
    CORR_DOC_REF_ID      VARCHAR2 (200 CHAR) ,
    TIPO                 VARCHAR2 (1 CHAR) ,
    ESTADO               VARCHAR2 (1 CHAR) ,
    PERIODO_ID           NUMBER(10) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.ORGANISATION.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.RES_COUNTRY_CODE
IS
  'CODIGO DEL PAIS DE RESIDENCIA DEL DECLARANTE' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.TIN
IS
  'NUMERO DE IDENTIFICACION ( TIN O GIIN)' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.TIN_ISSUED_BY
IS
  'CODIGO DEL PAIS AL QUE PERTENECE EL NUMERO DE IDENTIFICACION' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.NAME
IS
  'NOMBRE LEGAL DEL DECLARANTE' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.NAME_TYPE
IS
  'TIPO DE NOMBRE' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.LEGAL_ADDRESS_TYPE
IS
  'TIPO DE DIRECCION LEGAL' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.COUNTRY_CODE
IS
  'CODIGO DEL PAIS' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.ADDRESS_FREE
IS
  'DIRECCION' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.DOC_TYPE_INDIC
IS
  'IDENTIFICADOR DEL TIPO DE BLOQUE FATCA' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.DOC_REF_ID
IS
  'IDENTIFICADOR DEL BLOQUE' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.CORR_MESSAGE_REF_ID
IS
  'IDENTIFICADOR DEL MENSAJE ENVIADO ANTERIORMENTE Y SE ESTA CORRIGIENDO' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.CORR_DOC_REF_ID
IS
  'IDENTIFICADOR DEL DOCUMENTO ENVIADO ANTERIORMENTE Y SE ESTA CORRIGIENDO' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.ORGANISATION.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.ORGANISATION ADD CONSTRAINT ORGANISATION_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.PARAMETRO
  (
    ID                   NUMBER (10) NOT NULL ,
    PARAMETRO_ID         NUMBER (10) ,
    TIPO                 NUMBER (10) NOT NULL ,
    NOMBRE               VARCHAR2 (300 CHAR) NOT NULL ,
    DESCRIPCION          VARCHAR2 (500 CHAR) ,
    ESTADO               CHAR (1 CHAR) DEFAULT 'A' NOT NULL ,
    CODIGO               VARCHAR2 (50 CHAR) ,
    CODIGO_ETI           VARCHAR2 (100 CHAR) ,
    CODIGO_HABIL         CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    ENTERO               NUMBER (10) ,
    ENTERO_ETI           VARCHAR2 (100 CHAR) ,
    ENTERO_HABIL         CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    DECIMALES            NUMBER(26, 8) ,
    DECIMALES_ETI        VARCHAR2 (100 CHAR) ,
    DECIMALES_HABIL      CHAR (1 BYTE) DEFAULT 'N' NOT NULL ,
    TEXTO                VARCHAR2 (500 CHAR) ,
    TEXTO_ETI            VARCHAR2 (100 CHAR) ,
    TEXTO_HABIL          CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    TEXTO2               VARCHAR2 (500 CHAR) ,
    TEXTO_ETI2           VARCHAR2 (100 CHAR) ,
    TEXTO_HABIL2         CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    TEXTO3               VARCHAR2 (500 CHAR) ,
    TEXTO_ETI3           VARCHAR2 (100 CHAR) ,
    TEXTO_HABIL3         CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    FECHA                DATE ,
    FECHA_ETI            VARCHAR2 (100 CHAR) ,
    FECHA_HABIL          CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    HORA                 CHAR (5 CHAR) ,
    HORA_ETI             VARCHAR2 (100 CHAR) ,
    HORA_HABIL           CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    BOOLEANO             CHAR (1 CHAR) ,
    BOOLEANO_ETI         VARCHAR2 (100 CHAR) ,
    BOOLEANO_HABIL       CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    FUNCION              VARCHAR2 (100 CHAR) ,
    FUNCION_ETI          VARCHAR2 (100 CHAR) ,
    FUNCION_HABIL        CHAR (1 CHAR) DEFAULT 'N' NOT NULL ,
    FUNCION_MSG          VARCHAR2 (200 CHAR) ,
    PERMITE_HIJO         CHAR (1 CHAR) ,
    FECHA_MODIFICACION   DATE ,
    FECHA_CREACION       DATE NOT NULL ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR)
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.PARAMETRO.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.PARAMETRO_ID
IS
  'IDENTIFICADOR DEL PARAMETRO PADRE' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.TIPO
IS
  'IDENTIFICADOR DEL TIPO DE PARAMETRO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.NOMBRE
IS
  'NOMBRE DEL PARAMETRO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.DESCRIPCION
IS
  'DESCRIPCION DEL PARAMETRO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.ESTADO
IS
  'ESTADO DEL PARAMETRO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.CODIGO
IS
  'CODIGO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.CODIGO_ETI
IS
  'ETIQUITA A MOSTRAR PARA EL CAMPO CODIGO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.CODIGO_HABIL
IS
  'ESTADO DE CAMPO CODIGO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.ENTERO
IS
  'ENTERO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.ENTERO_ETI
IS
  'ETIQUITA A MOSTRAR PARA EL CAMPO ENTERO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.ENTERO_HABIL
IS
  'ESTADO DE CAMPO ENTERO' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.PARAMETRO.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  ALTER TABLE FATCA.PARAMETRO ADD CONSTRAINT PARAMETRO_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.PAYMENT
  (
    ID                   NUMBER (10) NOT NULL ,
    TYPE                 VARCHAR2 (10 CHAR) ,
    CURR_CODE            VARCHAR2 (3 CHAR) ,
    VALUE                VARCHAR2 (22 CHAR) ,
    ESTADO               VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE ,
    ACCOUNT_REPORT_ID    NUMBER (10) NOT NULL ,
    PERIODO_ID           NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.PAYMENT.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.PAYMENT.TYPE
IS
  'TIPO DE ABONO' ;
  COMMENT ON COLUMN FATCA.PAYMENT.CURR_CODE
IS
  'CODIGO DE MONEDA' ;
  COMMENT ON COLUMN FATCA.PAYMENT.VALUE
IS
  'MONTO DEL BALANCE' ;
  COMMENT ON COLUMN FATCA.PAYMENT.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.PAYMENT.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.PAYMENT.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.PAYMENT.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.PAYMENT ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.PERIODO
  (
    ID                   NUMBER (10) NOT NULL ,
    PERIODO              VARCHAR2 (4 CHAR) NOT NULL ,
    FECHA_COMPILACION    VARCHAR2 (25 CHAR) NOT NULL , 
    NOMBRE_PERIODO       VARCHAR2 (25 CHAR) NOT NULL ,
    ESTADO               VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.PERIODO.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.PERIODO.PERIODO
IS
  'NOMBRE DEL PERIODO' ;
  COMMENT ON COLUMN FATCA.PERIODO.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.PERIODO.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.PERIODO.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.PERIODO.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.PERIODO.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.PERIODO ADD CONSTRAINT PERIODO_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.PERSON
  (
    ID                    NUMBER (10) NOT NULL ,
    RES_COUNTRY_CODE      VARCHAR2 (2 CHAR) ,
    TIN                   VARCHAR2 (19 CHAR) ,
    TIN_ISSUED_BY         VARCHAR2 (2 CHAR) ,
    NAME_TYPE             VARCHAR2 (25 CHAR) ,
    PRECEDING_TITLE       VARCHAR2 (25 CHAR) ,
    TITLE                 VARCHAR2 (25 CHAR) ,
    FIRST_NAME            VARCHAR2 (60 CHAR) ,
    MIDDLE_NAME           VARCHAR2 (60 CHAR) ,
    NAME_PREFIX           VARCHAR2 (25 CHAR) ,
    LAST_NAME             VARCHAR2 (60 CHAR) ,
    GENERATION_IDENTIFIER VARCHAR2 (25 CHAR) ,
    SUFIX                 VARCHAR2 (25 CHAR) ,
    GENERAL_SUFIX         VARCHAR2 (25 CHAR) ,
    LEGAL_ADDRESS_TYPE    VARCHAR2 (10 CHAR) ,
    COUNTRY_CODE          VARCHAR2 (2 CHAR) ,
    ADDRESS_FREE          VARCHAR2 (500 CHAR) ,
    BIRTH_DATE            VARCHAR2 (10 CHAR) ,
    CITY                  VARCHAR2 (25 CHAR) ,
    CITY_SUB_ENTITY       VARCHAR2 (25 CHAR) ,
    COUNTRY_CODE_SOURCE   VARCHAR2 (2 CHAR) ,
    ESTADO                VARCHAR2 (1 CHAR) ,
    PERIODO_ID            NUMBER(10) ,
    USUARIO_CREACION      VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION  VARCHAR2 (7 CHAR) ,
    FECHA_CREACION        DATE NOT NULL ,
    FECHA_MODIFICACION    DATE
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.PERSON.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.PERSON.RES_COUNTRY_CODE
IS
  'CODIGO DEL PAIS DE RESIDENCIA DEL DECLARANTE' ;
  COMMENT ON COLUMN FATCA.PERSON.TIN
IS
  'NUMERO DE IDENTIFICACION ( TIN O GIIN)' ;
  COMMENT ON COLUMN FATCA.PERSON.TIN_ISSUED_BY
IS
  'CODIGO DEL PAIS AL QUE PERTENECE EL NUMERO DE IDENTIFICACION' ;
  COMMENT ON COLUMN FATCA.PERSON.NAME_TYPE
IS
  'TIPO DE NOMBRE' ;
  COMMENT ON COLUMN FATCA.PERSON.PRECEDING_TITLE
IS
  'TITULO' ;
  COMMENT ON COLUMN FATCA.PERSON.TITLE
IS
  'TITULO' ;
  COMMENT ON COLUMN FATCA.PERSON.FIRST_NAME
IS
  'PRIMER NOMBRE' ;
  COMMENT ON COLUMN FATCA.PERSON.MIDDLE_NAME
IS
  'SEGUNDO NOMBRE' ;
  COMMENT ON COLUMN FATCA.PERSON.NAME_PREFIX
IS
  'PREFIJO DE NOMBRE' ;
  COMMENT ON COLUMN FATCA.PERSON.LAST_NAME
IS
  'APELLIDOS' ;
  COMMENT ON COLUMN FATCA.PERSON.GENERATION_IDENTIFIER
IS
  'IDENTIFICADOR' ;
  COMMENT ON COLUMN FATCA.PERSON.SUFIX
IS
  'SUFIJO' ;
  COMMENT ON COLUMN FATCA.PERSON.GENERAL_SUFIX
IS
  'SUFIJO GENERAL' ;
  COMMENT ON COLUMN FATCA.PERSON.LEGAL_ADDRESS_TYPE
IS
  'TIPO DE DIRECCION LEGAL' ;
  COMMENT ON COLUMN FATCA.PERSON.COUNTRY_CODE
IS
  'CODIGO DEL PAIS DE RESIDENCIA' ;
  COMMENT ON COLUMN FATCA.PERSON.ADDRESS_FREE
IS
  'DIRECCION' ;
  COMMENT ON COLUMN FATCA.PERSON.BIRTH_DATE
IS
  'FECHA DE NACIMIENTO' ;
  COMMENT ON COLUMN FATCA.PERSON.CITY
IS
  'CIUDAD DE NACIMIENTO' ;
  COMMENT ON COLUMN FATCA.PERSON.CITY_SUB_ENTITY
IS
  'DISTRITO DE NACIMIENTO' ;
  COMMENT ON COLUMN FATCA.PERSON.COUNTRY_CODE_SOURCE
IS
  'CODIGO DEL PAIS DE NACIMIENTO' ;
  COMMENT ON COLUMN FATCA.PERSON.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.PERSON.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.PERSON.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.PERSON.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.PERSON.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.POOL_REPORT
  (
    ID                       NUMBER (10) NOT NULL ,
    ACCOUNT_COUNT            NUMBER (10) ,
    ACCOUNT_POOL_REPORT_TYPE VARCHAR2 (10 CHAR) ,
    POOL_BALANCE_CURR_CODE   VARCHAR2 (3 CHAR) ,
    POOL_BALANCE_VALUE       VARCHAR2 (22 CHAR) ,
    DOC_TYPE_INDIC           VARCHAR2 (10 CHAR) ,
    DOC_REF_ID               VARCHAR2 (200 CHAR) ,
    CORR_MESSAGE_REF_ID      VARCHAR2 (200 CHAR) ,
    CORR_DOC_REF_ID          VARCHAR2 (200 CHAR) ,
    ESTADO                   VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION         VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION     VARCHAR2 (7 CHAR) ,
    FECHA_CREACION           DATE NOT NULL ,
    FECHA_MODIFICACION       DATE ,
    REPORTING_GROUP_ID       NUMBER (10) NOT NULL ,
    PERIODO_ID               NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.POOL_REPORT.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.ACCOUNT_COUNT
IS
  'NUMERO DE CUENTAS EN POOL' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.ACCOUNT_POOL_REPORT_TYPE
IS
  'TIPO DE POOL' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.POOL_BALANCE_CURR_CODE
IS
  'CODIGO DE MONEDA' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.POOL_BALANCE_VALUE
IS
  'MONTO DE BALANCE AGREGADO ASOCIADO A LAS CUENTAS' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.DOC_TYPE_INDIC
IS
  'IDENTIFICADOR DEL TIPO DE BLOQUE FATCA' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.DOC_REF_ID
IS
  'IDENTIFICADOR DEL BLOQUE' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.CORR_MESSAGE_REF_ID
IS
  'IDENTIFICADOR DEL MENSAJE ENVIADO ANTERIORMENTE Y SE ESTA CORRIGIENDO' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.CORR_DOC_REF_ID
IS
  'IDENTIFICADOR DEL MENSAJE ENVIADO ANTERIORMENTE Y SE ESTA CORRIGIENDO' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.POOL_REPORT.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.POOL_REPORT ADD CONSTRAINT POOL_REPORT_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.REPORTING_FI
  (
    ID              NUMBER (10) NOT NULL ,
    ORGANISATION_ID NUMBER (10) NOT NULL ,
    PERIODO_ID      NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.REPORTING_FI.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  ALTER TABLE FATCA.REPORTING_FI ADD CONSTRAINT REPORTING_FI_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.REPORTING_GROUP
  (
    ID                   NUMBER (10) NOT NULL ,
    ESTADO               VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE ,
    FATCA_ID             NUMBER (10) NOT NULL ,
    PERIODO_ID           NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.REPORTING_GROUP.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.REPORTING_GROUP.ESTADO
IS
  'ESTADO' ;
  COMMENT ON COLUMN FATCA.REPORTING_GROUP.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.REPORTING_GROUP.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.REPORTING_GROUP.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.REPORTING_GROUP.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.REPORTING_GROUP ADD CONSTRAINT REPORTING_GROUP_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

CREATE TABLE FATCA.SUSTANTIAL_OWNER
  (
    ID                   NUMBER (10) NOT NULL ,
    ESTADO               VARCHAR2 (1 CHAR) ,
    USUARIO_CREACION     VARCHAR2 (7 CHAR) NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (7 CHAR) ,
    FECHA_CREACION       DATE NOT NULL ,
    FECHA_MODIFICACION   DATE ,
    ACCOUNT_REPORT_ID    NUMBER (10) NOT NULL ,
    PERSON_ID            NUMBER (10) NOT NULL ,
    PERIODO_ID           NUMBER (10) NOT NULL
  )  TABLESPACE FATCA_DAT;
COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.ID
IS
  'IDENTIFICADOR DEL REGISTRO' ;
  COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.USUARIO_CREACION
IS
  'USUARIO DE CREACION' ;
  COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.USUARIO_MODIFICACION
IS
  'USUARIO DE MODIFICACION' ;
  COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.FECHA_CREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.FECHA_MODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  ALTER TABLE FATCA.SUSTANTIAL_OWNER ADD CONSTRAINT SUSTANTIAL_OWNER_PK PRIMARY KEY ( ID ) USING INDEX  TABLESPACE FATCA_IDX;

ALTER TABLE FATCA.ACCIONISTAS ADD CONSTRAINT ACCIONISTAS_PERIODO_FK FOREIGN KEY ( PERIODO_ID ) REFERENCES FATCA.PERIODO ( ID ) ;

ALTER TABLE FATCA.ACCOUNT_REPORT ADD CONSTRAINT ACCOUNT_REPORT_ORGANISATION_FK FOREIGN KEY ( ORGANISATION_ID ) REFERENCES FATCA.ORGANISATION ( ID ) ;

ALTER TABLE FATCA.ACCOUNT_REPORT ADD CONSTRAINT ACCOUNT_REPORT_PERSON_FK FOREIGN KEY ( PERSON_ID ) REFERENCES FATCA.PERSON ( ID ) ;

ALTER TABLE FATCA.ACCOUNT_REPORT ADD CONSTRAINT ACCOUNT_REPORTING_GROUP_FK FOREIGN KEY ( REPORTING_GROUP_ID ) REFERENCES FATCA.REPORTING_GROUP ( ID ) ;

ALTER TABLE FATCA.CUENTAS ADD CONSTRAINT CUENTAS_PERIODO_FK FOREIGN KEY ( PERIODO_ID ) REFERENCES FATCA.PERIODO ( ID ) ;

ALTER TABLE FATCA.FATCA ADD CONSTRAINT FATCA_FATCA_OECD_FK FOREIGN KEY ( FATCA_OECD_ID ) REFERENCES FATCA.FATCA_OECD ( ID ) ;

ALTER TABLE FATCA.FATCA_OECD ADD CONSTRAINT FATCA_OECD_PERIODO_FK FOREIGN KEY ( PERIODO_ID ) REFERENCES FATCA.PERIODO ( ID ) ;

ALTER TABLE FATCA.FATCA ADD CONSTRAINT FATCA_REPORTING_FI_FK FOREIGN KEY ( REPORTING_FI_ID ) REFERENCES FATCA.REPORTING_FI ( ID ) ;

ALTER TABLE FATCA.INTERMEDIARY ADD CONSTRAINT INTERMEDIARY_ORGANISATION_FK FOREIGN KEY ( ORGANISATION_ID ) REFERENCES FATCA.ORGANISATION ( ID ) ;

ALTER TABLE FATCA.INTERMEDIARY ADD CONSTRAINT INTERMEDIARY_RPT_GROUP_FK FOREIGN KEY ( REPORTING_GROUP_ID ) REFERENCES FATCA.REPORTING_GROUP ( ID ) ;

-- ALTER TABLE FATCA.LOG ADD CONSTRAINT LOG_ACCIONISTAS_FK FOREIGN KEY ( ACCIONISTAS_ID ) REFERENCES FATCA.ACCIONISTAS ( ID ) ;

-- ALTER TABLE FATCA.LOG ADD CONSTRAINT LOG_CUENTAS_FK FOREIGN KEY ( CUENTAS_ID ) REFERENCES FATCA.CUENTAS ( ID ) ;

ALTER TABLE FATCA.PARAMETRO ADD CONSTRAINT PARAMETRO_PARAMETRO_FK FOREIGN KEY ( PARAMETRO_ID ) REFERENCES FATCA.PARAMETRO ( ID ) ;

ALTER TABLE FATCA.PAYMENT ADD CONSTRAINT PAYMENT_ACCOUNT_REPORT_FK FOREIGN KEY ( ACCOUNT_REPORT_ID ) REFERENCES FATCA.ACCOUNT_REPORT ( ID ) ;

ALTER TABLE FATCA.POOL_REPORT ADD CONSTRAINT POOL_REPORT_REPORTING_GROUP_FK FOREIGN KEY ( REPORTING_GROUP_ID ) REFERENCES FATCA.REPORTING_GROUP ( ID ) ;

ALTER TABLE FATCA.REPORTING_FI ADD CONSTRAINT REPORTING_FI_ORGANISATION_FK FOREIGN KEY ( ORGANISATION_ID ) REFERENCES FATCA.ORGANISATION ( ID ) ;

ALTER TABLE FATCA.REPORTING_GROUP ADD CONSTRAINT REPORTING_GROUP_FATCA_FK FOREIGN KEY ( FATCA_ID ) REFERENCES FATCA.FATCA ( ID ) ;

ALTER TABLE FATCA.SUSTANTIAL_OWNER ADD CONSTRAINT SUSTANTIAL_ACCOUNT_REPORT_FK FOREIGN KEY ( ACCOUNT_REPORT_ID ) REFERENCES FATCA.ACCOUNT_REPORT ( ID ) ;

ALTER TABLE FATCA.SUSTANTIAL_OWNER ADD CONSTRAINT SUSTANTIAL_OWNER_PERSON_FK FOREIGN KEY ( PERSON_ID ) REFERENCES FATCA.PERSON ( ID ) ;

CREATE INDEX IDX_FATCA_00            ON FATCA.FATCA(REPORTING_FI_ID)              TABLESPACE FATCA_IDX;
CREATE INDEX IDX_FATCA_01            ON FATCA.FATCA(FATCA_OECD_ID)                TABLESPACE FATCA_IDX;
CREATE INDEX IDX_PERSON_00           ON FATCA.PERSON(TIN)                         TABLESPACE FATCA_IDX;
CREATE INDEX IDX_ORGANISATION_00     ON FATCA.ORGANISATION(TIN)                   TABLESPACE FATCA_IDX;
CREATE INDEX IDX_ACCOUNT_REPORT_00   ON FATCA.ACCOUNT_REPORT(REPORTING_GROUP_ID)  TABLESPACE FATCA_IDX;
CREATE INDEX IDX_ACCOUNT_REPORT_01   ON FATCA.ACCOUNT_REPORT(PERSON_ID)           TABLESPACE FATCA_IDX;
CREATE INDEX IDX_ACCOUNT_REPORT_02   ON FATCA.ACCOUNT_REPORT(ORGANISATION_ID)     TABLESPACE FATCA_IDX;
CREATE INDEX IDX_SUSTANTIAL_OWNER_01 ON FATCA.SUSTANTIAL_OWNER(ACCOUNT_REPORT_ID) TABLESPACE FATCA_IDX;
CREATE INDEX IDX_SUSTANTIAL_OWNER_02 ON FATCA.SUSTANTIAL_OWNER(PERSON_ID)         TABLESPACE FATCA_IDX;
CREATE INDEX IDX_INTERMEDIARY_01     ON FATCA.INTERMEDIARY(REPORTING_GROUP_ID)    TABLESPACE FATCA_IDX;
CREATE INDEX IDX_INTERMEDIARY_02     ON FATCA.INTERMEDIARY(ORGANISATION_ID)       TABLESPACE FATCA_IDX;
CREATE INDEX IDX_POOL_REPORT_01      ON FATCA.POOL_REPORT(REPORTING_GROUP_ID)     TABLESPACE FATCA_IDX;
CREATE INDEX IDX_REPORTING_FI_01     ON FATCA.REPORTING_FI(ORGANISATION_ID)       TABLESPACE FATCA_IDX;
CREATE INDEX IDX_REPORTING_GROUP_01  ON FATCA.REPORTING_GROUP(FATCA_ID)           TABLESPACE FATCA_IDX;
CREATE INDEX IDX_PAYMENT_01          ON FATCA.PAYMENT(ACCOUNT_REPORT_ID)          TABLESPACE FATCA_IDX;


COMMENT ON TABLE FATCA.BATCH_STEP_EXECUTION_CONTEXT IS 'TABLAS DE LA LIBRERIA SPRING BATCH PARA EN MANEJO DE TAREAS: ALMACENA INFORMACIÃ“N DEL CONTEXTO DEL PASO';
COMMENT ON TABLE FATCA.BATCH_STEP_EXECUTION         IS 'TABLAS DE LA LIBRERIA SPRING BATCH PARA EN MANEJO DE TAREAS: ALMACENA INFORMACIÃ“N DE LA EJECUCIÃ“N DEL PASO';
COMMENT ON TABLE FATCA.BATCH_JOB_INSTANCE           IS 'TABLAS DE LA LIBRERIA SPRING BATCH PARA EN MANEJO DE TAREAS: INSTANCIA DE LA TAREA';
COMMENT ON TABLE FATCA.BATCH_JOB_EXECUTION_PARAMS   IS 'TABLAS DE LA LIBRERIA SPRING BATCH PARA EN MANEJO DE TAREAS: ALMACENA INFORMACIÃ“N DE LOS PARAMETROS DE LA TAREA';
COMMENT ON TABLE FATCA.BATCH_JOB_EXECUTION_CONTEXT  IS 'TABLAS DE LA LIBRERIA SPRING BATCH PARA EN MANEJO DE TAREAS: ALMACENA INFORMACIÃ“N DEL CONTEXTO DE LA TAREA';
COMMENT ON TABLE FATCA.BATCH_JOB_EXECUTION          IS 'TABLAS DE LA LIBRERIA SPRING BATCH PARA EN MANEJO DE TAREAS: ALMACENA INFORMACIÃ“N DE LA EJECUCIÃ“N DE LA TAREA';

COMMENT ON TABLE FATCA.QRTZ_TRIGGERS                IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_SIMPROP_TRIGGERS        IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_SIMPLE_TRIGGERS         IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_SCHEDULER_STATE         IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_PAUSED_TRIGGER_GRPS     IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_LOCKS                   IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_JOB_DETAILS             IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_FIRED_TRIGGERS          IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_CRON_TRIGGERS           IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_CALENDARS               IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';
COMMENT ON TABLE FATCA.QRTZ_BLOB_TRIGGERS           IS 'TABLAS DE LA LIBRERIA QUARTZ EN ENTORNO DE CLUSTER';

COMMENT ON TABLE FATCA.PERIODO                      IS 'TABLA DE PERIODO';
COMMENT ON TABLE FATCA.CUENTAS                      IS 'TABLA DE CUENTAS';
COMMENT ON TABLE FATCA.ACCIONISTAS                  IS 'TABLA DE ACCIONISTAS, SE ALIMENTA DEL PROCESO DE CARGA DEL ARCHIVO EXCEL';
COMMENT ON TABLE FATCA.LOG                          IS 'TABLA DE LOG DE ERRORES';
COMMENT ON TABLE FATCA.PARAMETRO                    IS 'TABLA DE PARAMETROS';

COMMENT ON TABLE FATCA.SUSTANTIAL_OWNER             IS 'TABLA DE ACCIONISTAS';
COMMENT ON TABLE FATCA.REPORTING_GROUP              IS 'TABLA DETALLE, CADA NIVEL QUE SE REPORTA EN EL ARCHIVO XML DENTRO DEL TAG FATCA';
COMMENT ON TABLE FATCA.REPORTING_FI                 IS 'TABLA REPORTING FI REPRESENTA A LA ENTIDAD FINANCIERA QUE REPORA LAS CUENTAS';
COMMENT ON TABLE FATCA.POOL_REPORT                  IS 'TABLA DE POOL REPORT';
COMMENT ON TABLE FATCA.PERSON                       IS 'TABLA DE PERSONAS';
COMMENT ON TABLE FATCA.PAYMENT                      IS 'TABLA DE PAYMENT';
COMMENT ON TABLE FATCA.ORGANISATION                 IS 'TABLA DE ORGANIZACIONES';
COMMENT ON TABLE FATCA.INTERMEDIARY                 IS 'TABLA DE INTERMEDIARIOS';
COMMENT ON TABLE FATCA.FATCA_OECD                   IS 'TABLA MAESTRA, CABECERA DEL ARCHIVO XML';
COMMENT ON TABLE FATCA.FATCA                        IS 'TABLA DETALLE, CADA NIVEL QUE SE REPORTA EN EL ARCHIVO XML DENTRO DEL TAG FATCA_OECD';
COMMENT ON TABLE FATCA.ACCOUNT_REPORT               IS 'TABLA DE CUENTAS REPORTADAS';

COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_APELLIDO_MATERNO IS 'APELLIDO MATERNO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_APELLIDO_PATERNO IS 'APELLIDO PATERNO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_CIUDAD IS 'CIUDAD DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_CODIGO_POSTAL IS 'CODIGO POSTAL DE LA DIRECCION DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_DEPARTAMENTO IS 'DEPARTAMENTO DEL DOMICILIO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_DIRECCION IS 'DIRECCION DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_DISTRITO IS 'DISTRITO DEL DOMICILIO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_NOMBRE IS 'NOMBRE DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_NRO_ACCIONES IS 'NRO DE ACCIONES DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_NRO_DOCUMENTO IS 'NRO DE DOCUMENTO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_PAIS_NACIMIENTO IS 'PAIS DE NACIMIEMTO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_PAIS_RESIDENCIA IS 'PAIS DE RESIDENCIA DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_PAIS_1 IS 'PAÍS DE RESIDENCIA 1 DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_PAIS_2 IS 'PAÍS DE RESIDENCIA 2 DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_PAIS_3 IS 'PAÍS DE RESIDENCIA 3 DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_PORC_ACCIONES IS 'PORCENTAJE DE ACCIONES DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_TIN_1 IS 'CODIGO TIN 1 DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_TIN_2 IS 'CODIGO TIN 2 DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_TIN_3 IS 'CODIGO TIN 3 DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.ACC_TIPO_DOCUMENTO IS 'TIPO DE DOCUMENTO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.APD_NOMBRE IS 'NOMBRE DEL APODERADO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.APD_NRO_DOCUMENTO IS 'NRO DE DOCUMENTO DEL APODERADO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.APD_TIPO_DOCUMENTO IS 'TIPO DE DOCUMEMTO DEL APODERADO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.EMP_CODIGO_CLIENTE IS 'CÓDIGO DE CLIENTE DEL PROPIETARIO DE LA CUENTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.EMP_NRO_DOCUMENTO IS 'NRO DE DOCUMENTO DEL PROPIETARIO DE LA CUENTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.EMP_RAZON_SOCIAL IS 'RAZÓN SOCIAL DEL PROPIETARIO DE LA CUENTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.EMP_TIPO_DOCUMENTO IS 'TIPO DE DOCUMEMTO DEL PROPIETARIO DE LA CUENTA';
COMMENT ON COLUMN FATCA.ACCIONISTAS.FECHA_RECEPCION IS 'FECHA DE RECEPCIÓN';
COMMENT ON COLUMN FATCA.ACCIONISTAS.FECHA_REGISTRO IS 'FECHA DE REGISTRO';
COMMENT ON COLUMN FATCA.FATCA.FATCA_OECD_ID IS 'CÓDIGO DEL BLOQUE FATCA OECD';
COMMENT ON COLUMN FATCA.FATCA.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.FATCA.REPORTING_FI_ID IS 'CÓDIGO DEL BLOQUE REPORTING FI';
COMMENT ON COLUMN FATCA.FATCA_OECD.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.INTERMEDIARY.ORGANISATION_ID IS 'CÓDIGO DE LA ORGANIZACIÓN';
COMMENT ON COLUMN FATCA.INTERMEDIARY.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.INTERMEDIARY.REPORTING_GROUP_ID IS 'CÓDIGO DEL BLOQUE REPORTING GROUP';
COMMENT ON COLUMN FATCA.ORGANISATION.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.ORGANISATION.TIPO IS 'TIPO DE ORGANIZACION (PARA DIFERENCIAS SI ES UN FI)';
COMMENT ON COLUMN FATCA.ACCIONISTAS.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.ESTADO IS 'ESTADO DEL REGISTRO';
COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.ORGANISATION_ID IS 'CÓDIGO DE LA ORGANIZACIÓN';
COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.PERSON_ID IS 'CÓDIGO DE LA PERSONA';
COMMENT ON COLUMN FATCA.ACCOUNT_REPORT.REPORTING_GROUP_ID IS 'CÓDIGO DEL BLOQUE REPORTING GROUP';
COMMENT ON COLUMN FATCA.PAYMENT.ACCOUNT_REPORT_ID IS 'CÓDIGO DEL ACCOUNT REPORT';
COMMENT ON COLUMN FATCA.PAYMENT.ESTADO IS 'ESTADO DEL REGISTRO';
COMMENT ON COLUMN FATCA.PAYMENT.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.PERIODO.FECHA_COMPILACION IS 'NOMBRE DEL PERIODO';
COMMENT ON COLUMN FATCA.PERIODO.NOMBRE_PERIODO IS 'FECHA DE COMPILACIÓN DEL PERIODO';
COMMENT ON COLUMN FATCA.PERSON.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.POOL_REPORT.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.POOL_REPORT.REPORTING_GROUP_ID IS 'CÓDIGO DEL BLOQUE REPORTING GROUP';
COMMENT ON COLUMN FATCA.REPORTING_FI.ORGANISATION_ID IS 'CÓDIGO DE LA ORGANIZACIÓN';
COMMENT ON COLUMN FATCA.REPORTING_FI.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.REPORTING_GROUP.FATCA_ID IS 'CÓDIGO DEL BLOQUE FATCA';
COMMENT ON COLUMN FATCA.REPORTING_GROUP.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.ACCOUNT_REPORT_ID IS 'CÓDIGO DEL ACCOUNT REPORT';
COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.ESTADO IS 'ESTADO DEL REGISTRO';
COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.SUSTANTIAL_OWNER.PERSON_ID IS 'CÓDIGO DE LA PERSONA';
COMMENT ON COLUMN FATCA.CUENTAS.CODIGO_POSTAL IS 'CÓDIGO POSTAL DEL DOMICILIO DEL PROPIETARIO DE LA CUENTA';
COMMENT ON COLUMN FATCA.CUENTAS.MONEDA_501 IS 'CÓDIGO DE MONEDA ISO 501';
COMMENT ON COLUMN FATCA.CUENTAS.MONEDA_502 IS 'CÓDIGO DE MONEDA ISO 502';
COMMENT ON COLUMN FATCA.CUENTAS.MONEDA_503 IS 'CÓDIGO DE MONEDA ISO 503';
COMMENT ON COLUMN FATCA.CUENTAS.MONEDA_504 IS 'CÓDIGO DE MONEDA ISO 504';
COMMENT ON COLUMN FATCA.CUENTAS.MONTO_501 IS 'MONTO ABONANDO EN LA CUENTA 501';
COMMENT ON COLUMN FATCA.CUENTAS.MONTO_502 IS 'MONTO ABONANDO EN LA CUENTA 502';
COMMENT ON COLUMN FATCA.CUENTAS.MONTO_503 IS 'MONTO ABONANDO EN LA CUENTA 503';
COMMENT ON COLUMN FATCA.CUENTAS.MONTO_504 IS 'MONTO ABONANDO EN LA CUENTA 504';
COMMENT ON COLUMN FATCA.CUENTAS.ORIGEN_501 IS 'CÓDIGO ISO DEL PAIS DE ORIGEN DEL DEPOSITO 501';
COMMENT ON COLUMN FATCA.CUENTAS.ORIGEN_502 IS 'CÓDIGO ISO DEL PAIS DE ORIGEN DEL DEPOSITO 502';
COMMENT ON COLUMN FATCA.CUENTAS.ORIGEN_503 IS 'CÓDIGO ISO DEL PAIS DE ORIGEN DEL DEPOSITO 503';
COMMENT ON COLUMN FATCA.CUENTAS.ORIGEN_504 IS 'CÓDIGO ISO DEL PAIS DE ORIGEN DEL DEPOSITO 504';
COMMENT ON COLUMN FATCA.CUENTAS.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.CUENTAS.PERIODO_PARTICION IS 'CÓDIGO DE LA PARTICIÓN A USAR';
COMMENT ON COLUMN FATCA.LOG.ACCIONISTAS_ID IS 'CÓDIGO DEL ACCIONISTA';
COMMENT ON COLUMN FATCA.LOG.CUENTAS_ID IS 'CÓDIGO DE LA CUENTA';
COMMENT ON COLUMN FATCA.LOG.PERIODO_ID IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN FATCA.LOG.PROCESO_ID IS 'CÓDIGO DEL PROCESO';

spool off
