spool 04_createExternalTable.log


CREATE TABLE FATCA.CUENTAS_EXT 
(
   BLANCO                    VARCHAR2( 3 CHAR), 
   CODIGO_GIIN               VARCHAR2(19 CHAR), 
   PAIS_BANCO                VARCHAR2( 3 CHAR), 
   PAIS_RECEPTOR             VARCHAR2( 3 CHAR), 
   TIPO_REPORTE              VARCHAR2( 5 CHAR), 
   CODIGO_REFERENCIA         VARCHAR2( 5 CHAR), 
   PERIODO_INFORMADO         VARCHAR2(10 CHAR), 
   FECHA_COMPILACION         VARCHAR2(19 CHAR), 
   ID_ENTIDAD                VARCHAR2( 5 CHAR), 
   CODIGO_CLIENTE            VARCHAR2( 8 CHAR), 
   TIPO_DOCUMENTO            VARCHAR2( 6 CHAR), 
   NRO_DOCUMENTO             VARCHAR2(16 CHAR), 
   CLASIFICACION             VARCHAR2(20 CHAR), 
   TIN                       VARCHAR2(20 CHAR), 
   NOMBRE                    VARCHAR2(60 CHAR), 
   APELLIDO                  VARCHAR2(60 CHAR), 
   DIRECCION                 VARCHAR2(60 CHAR), 
   PAIS_RESIDENCIA           VARCHAR2( 3 CHAR), 
   CIUDAD                    VARCHAR2(60 CHAR), 
   PROVINCIA                 VARCHAR2(60 CHAR), 
   CODIGO_POSTAL             VARCHAR2( 5 CHAR), 
   REFERENCIA_DIRECCION      VARCHAR2(60 CHAR), 
   FECHA_NACIMIENTO          VARCHAR2(10 CHAR), 
   GRUPO_REPORTE             VARCHAR2(20 CHAR), 
   ID_DOC_SPEC               VARCHAR2(25 CHAR), 
   ID_REPORTE                VARCHAR2(25 CHAR), 
   NRO_CUENTA                VARCHAR2(24 CHAR), 
   TITULAR_CUENTA            VARCHAR2(60 CHAR), 
   PROPIETARIOS_SUSTANCIALES VARCHAR2(60 CHAR), 
   SALDO_CUENTA              VARCHAR2(25 CHAR), 
   SALDO_MONEDA              VARCHAR2( 3 CHAR), 
   VALOR_NOMINAL             VARCHAR2(25 CHAR), 
   VALOR_NOMINAL_MONEDA      VARCHAR2( 3 CHAR), 
   VALOR_MERCADO             VARCHAR2(25 CHAR), 
   VALOR_MERCADO_MONEDA      VARCHAR2( 3 CHAR), 
   ENTIDAD_CONTRATO          VARCHAR2( 6 CHAR), 
   TIPO_FONDO                VARCHAR2( 4 CHAR), 
   MONEDA_501                VARCHAR2( 3 CHAR), 
   MONTO_501                 VARCHAR2(25 CHAR), 
   ORIGEN_501                VARCHAR2( 2 CHAR), 
   MONEDA_502                VARCHAR2( 3 CHAR), 
   MONTO_502                 VARCHAR2(25 CHAR), 
   ORIGEN_502                VARCHAR2( 2 CHAR), 
   MONEDA_503                VARCHAR2( 3 CHAR), 
   MONTO_503                 VARCHAR2(25 CHAR), 
   ORIGEN_503                VARCHAR2( 2 CHAR), 
   MONEDA_504                VARCHAR2( 3 CHAR), 
   MONTO_504                 VARCHAR2(25 CHAR), 
   ORIGEN_504                VARCHAR2( 2 CHAR), 
   CODIGO_CUSTODIO           VARCHAR2( 4 CHAR), 
   ADMINISTRACION_MERCADO    VARCHAR2( 2 CHAR)
) 
ORGANIZATION EXTERNAL ( 
  TYPE ORACLE_LOADER 
  DEFAULT DIRECTORY FATCA_LOAD_DIR 
  ACCESS PARAMETERS 
      ( RECORDS DELIMITED BY NEWLINE CHARACTERSET UTF8
        BADFILE FATCA_OUT_DIR: 'CUENTAS.BAD'
        LOGFILE FATCA_OUT_DIR: 'CUENTAS.LOG'
        FIELDS TERMINATED BY '|'
      ) 
  LOCATION ( 'CUENTAS.txt' )
) 
REJECT LIMIT 0 ;

/*
CREATE TABLE FATCA.ACCIONISTAS_EXT
(
	EMP_CODIGO_CLIENTE VARCHAR2(8 CHAR), 
	EMP_TIPO_DOCUMENTO VARCHAR2(3 CHAR), 
	EMP_NRO_DOCUMENTO VARCHAR2(11 CHAR), 
	EMP_RAZON_SOCIAL VARCHAR2(60 CHAR), 
	ACC_TIPO_DOCUMENTO VARCHAR2(3 CHAR), 
	ACC_NUMERO_DOCUMENTO VARCHAR2(11 CHAR), 
	ACC_NOMBRE VARCHAR2(20 CHAR), 
	ACC_APELLIDO_PATERNO VARCHAR2(20 CHAR), 
	ACC_APELLIDO_MATERNO VARCHAR2(20 CHAR), 
	ACC_DIRECCION VARCHAR2(66 CHAR), 
	ACC_DEPARTAMENTO VARCHAR2(40 CHAR), 
	ACC_CIUDAD VARCHAR2(40 CHAR), 
	ACC_DISTRITO VARCHAR2(40 CHAR), 
	ACC_TIN VARCHAR2(20 CHAR), 
	ACC_PAIS_RESIDENCIA VARCHAR2(40 CHAR), 
	ACC_PORCENTAJE VARCHAR2(10 CHAR), 
	ACC_FECHA_NACIMIENTO VARCHAR2(10 CHAR),
  LINEA VARCHAR2(25 CHAR)
)
ORGANIZATION EXTERNAL ( 
  TYPE ORACLE_LOADER 
  DEFAULT DIRECTORY FATCA_LOAD_DIR 
  ACCESS PARAMETERS 
      ( RECORDS DELIMITED BY NEWLINE CHARACTERSET UTF8
        BADFILE FATCA_OUT_DIR: 'ACCIONISTAS.BAD'
        LOGFILE FATCA_OUT_DIR: 'ACCIONISTAS.LOG'
        FIELDS  (
			EMP_CODIGO_CLIENTE            POSITION(1  :8  ),
			EMP_TIPO_DOCUMENTO            POSITION(9  :11 ),
			EMP_NRO_DOCUMENTO             POSITION(12 :22 ),
			EMP_RAZON_SOCIAL              POSITION(23 :82 ),
			ACC_TIPO_DOCUMENTO            POSITION(83 :85 ),
			ACC_NUMERO_DOCUMENTO          POSITION(86 :96 ),
			ACC_NOMBRE                    POSITION(97 :116),
			ACC_APELLIDO_PATERNO          POSITION(117:136),
			ACC_APELLIDO_MATERNO          POSITION(137:156),
			ACC_DIRECCION                 POSITION(157:222),
			ACC_DEPARTAMENTO              POSITION(223:262),
			ACC_CIUDAD                    POSITION(263:302),
			ACC_DISTRITO                  POSITION(303:342),
			ACC_TIN                       POSITION(343:362),
			ACC_PAIS_RESIDENCIA           POSITION(363:402),
			ACC_PORCENTAJE                POSITION(403:412),
			ACC_FECHA_NACIMIENTO          POSITION(413:422),
      LINEA                         RECNUM
        )
      ) 
  LOCATION ( 'ACCIONISTAS.txt' )
) 
REJECT LIMIT 0 ;
*/

spool off
