spool 09_createPackage.log

CREATE OR REPLACE PACKAGE FATCA.PKG_CONSULTAS IS
  PROCEDURE SP_CONSULTA_CLIENTE(P_REF_CURSOR OUT SYS_REFCURSOR, P_ROWS_NUM NUMBER, P_PAGESIZE NUMBER, P_PAGE NUMBER, P_PERIODO NUMBER, P_ENTIDADCONTRATO VARCHAR2, P_NROCUENTA VARCHAR2, P_NOMBRE VARCHAR2, P_ESTADO VARCHAR2, P_CODIGOCLIENTE VARCHAR2);
END PKG_CONSULTAS;
/

CREATE OR REPLACE PACKAGE FATCA.PKG_PROCESOS_ENTRADA IS

  P_ID_TABLA_MONEDA CONSTANT NUMBER := 60;
  P_ID_TABLA_PAIS CONSTANT NUMBER := 257;
  P_ID_TABLA_TIPO_PERSONA CONSTANT NUMBER := 247;
  P_PERSONA_NATURAL CONSTANT NUMBER := 248;
  P_TIPO_POOL CONSTANT NUMBER := 240;

  TYPE T_CUENTA IS RECORD(
    ID_CUENTA                    DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_GIIN                  DBMS_SQL.VARCHAR2_TABLE,
    PAIS_BANCO                   DBMS_SQL.VARCHAR2_TABLE,
    PAIS_RECEPTOR                DBMS_SQL.VARCHAR2_TABLE,
    TIPO_REPORTE                 DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_REFERENCIA            DBMS_SQL.VARCHAR2_TABLE,
    PERIODO_INFORMADO            DBMS_SQL.VARCHAR2_TABLE,
    FECHA_COMPILACION            DBMS_SQL.VARCHAR2_TABLE,
    ID_ENTIDAD                   DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_CLIENTE               DBMS_SQL.VARCHAR2_TABLE,
    TIPO_DOCUMENTO               DBMS_SQL.VARCHAR2_TABLE,
    NRO_DOCUMENTO                DBMS_SQL.VARCHAR2_TABLE,
    CLASIFICACION                DBMS_SQL.VARCHAR2_TABLE,
    TIN                          DBMS_SQL.VARCHAR2_TABLE,
    NOMBRE                       DBMS_SQL.VARCHAR2_TABLE,
    APELLIDO                     DBMS_SQL.VARCHAR2_TABLE,
    DIRECCION                    DBMS_SQL.VARCHAR2_TABLE,
    PAIS_RESIDENCIA              DBMS_SQL.VARCHAR2_TABLE,
    CIUDAD                       DBMS_SQL.VARCHAR2_TABLE,
    PROVINCIA                    DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_POSTAL                DBMS_SQL.VARCHAR2_TABLE,
    REFERENCIA_DIRECCION         DBMS_SQL.VARCHAR2_TABLE,
    FECHA_NACIMIENTO             DBMS_SQL.VARCHAR2_TABLE,
    GRUPO_REPORTE                DBMS_SQL.VARCHAR2_TABLE,
    ID_DOC_SPEC                  DBMS_SQL.VARCHAR2_TABLE,
    ID_REPORTE                   DBMS_SQL.VARCHAR2_TABLE,
    NRO_CUENTA                   DBMS_SQL.VARCHAR2_TABLE,
    TITULAR_CUENTA               DBMS_SQL.VARCHAR2_TABLE,
    PROPIETARIOS_SUSTANCIALES    DBMS_SQL.VARCHAR2_TABLE,
    SALDO_CUENTA                 DBMS_SQL.VARCHAR2_TABLE,
    SALDO_MONEDA                 DBMS_SQL.VARCHAR2_TABLE,
    ENTIDAD_CONTRATO             DBMS_SQL.VARCHAR2_TABLE,
    VALOR_NOMINAL                DBMS_SQL.VARCHAR2_TABLE,
    VALOR_NOMINAL_MONEDA         DBMS_SQL.VARCHAR2_TABLE,
    VALOR_MERCADO                DBMS_SQL.VARCHAR2_TABLE,
    VALOR_MERCADO_MONEDA         DBMS_SQL.VARCHAR2_TABLE,
    TIPO_FONDO                   DBMS_SQL.VARCHAR2_TABLE,
    MONTO_501                    DBMS_SQL.VARCHAR2_TABLE,
    MONTO_502                    DBMS_SQL.VARCHAR2_TABLE,
    MONTO_503                    DBMS_SQL.VARCHAR2_TABLE,
    MONTO_504                    DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_501                   DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_502                   DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_503                   DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_504                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_501                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_502                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_503                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_504                   DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_CUSTODIO              DBMS_SQL.VARCHAR2_TABLE,
    ADMINISTRACION_MERCADO       DBMS_SQL.VARCHAR2_TABLE,
    PERIODO_ID                   DBMS_SQL.VARCHAR2_TABLE,
    LINEA                        DBMS_SQL.VARCHAR2_TABLE,
    ESTADO                       DBMS_SQL.VARCHAR2_TABLE,
    ESTADO_PROCESO               DBMS_SQL.VARCHAR2_TABLE,
    MENSAJE                      DBMS_SQL.VARCHAR2_TABLE
  );

  PROCEDURE SP_CARGAR_CUENTAS(USUARIO VARCHAR2, ID_PROCESO NUMBER, FILAS_LEIDAS OUT NUMBER, FILAS_ESCRITAS OUT NUMBER, ESTADO OUT VARCHAR2, DESCRIPCION OUT VARCHAR2);
  PROCEDURE SP_VALIDAR_CUENTA_PROCESO(P_CUENTA T_CUENTA, MENSAJE_OUT OUT VARCHAR2);
  PROCEDURE SP_VALIDAR_CUENTA(P_CUENTA_EXT T_CUENTA, K NUMBER, P_POOL_MARCAS VARCHAR2, P_CUENTA OUT T_CUENTA);
  PROCEDURE SP_COMPARAR_VARIABLES(P_VARIABLE_A VARCHAR2, P_VARIABLE_B VARCHAR2, P_VALOR_NUEVO OUT VARCHAR2, P_NOMBRE_CAMPO VARCHAR2, ESTADO VARCHAR2, MENSAJE OUT VARCHAR2);

  FUNCTION SF_OBTENER_PAIS_X_CODIGO_HOST(P_CODIGO_PAIS VARCHAR2) RETURN VARCHAR2;
  FUNCTION SF_OBTENER_MONE_X_CODIGO_HOST(P_CODIGO_MONEDA VARCHAR2) RETURN VARCHAR2;
  FUNCTION SF_OBTENER_NEXTVAL_CUENTA RETURN NUMBER;

END PKG_PROCESOS_ENTRADA;
/

CREATE OR REPLACE PACKAGE FATCA.PKG_PROCESOS_SALIDA AS

  P_REGLAS_MARCAS  NUMBER := 504;
  P_LIMPIAR        NUMBER := 256;
  P_TEST           NUMBER := 251;
  P_ACCIONISTAS    NUMBER := 255;
  P_TIPO_POOL      NUMBER := 240;
  P_TIPO_ACCOUNT   NUMBER := 229;
  P_PAYMENT_501    NUMBER := 236;
  P_PAYMENT_502    NUMBER := 237;
  P_PAYMENT_503    NUMBER := 238;
  P_PAYMENT_504    NUMBER := 239;
  P_MESSAGE_SPEC   VARCHAR2(1) := '1';
  P_ACCOUNT_REPORT VARCHAR2(1) := '2';
  P_POOL_REPORT    VARCHAR2(1) := '3';
  P_REPORTING_FI   VARCHAR2(1) := '4';
  P_INTERMEDIARY   VARCHAR2(1) := '5';
  P_COL_SALDO      VARCHAR2(25) := 'SALDO';
  P_COL_VALOR      VARCHAR2(25) := 'VALOR MERCADO';
  P_GIN_FONDO      NUMBER := 20; -- JMD9QR.00000.SP.604
  P_GIN_BANCO      NUMBER := 18; -- JMD9QR.00000.SP.604
  P_PAIS_REPORTA   NUMBER := 553;

  TYPE T_CUENTA IS RECORD(
    ID_CUENTA                    DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_GIIN                  DBMS_SQL.VARCHAR2_TABLE,
    PAIS_BANCO                   DBMS_SQL.VARCHAR2_TABLE,
    PAIS_RECEPTOR                DBMS_SQL.VARCHAR2_TABLE,
    TIPO_REPORTE                 DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_REFERENCIA            DBMS_SQL.VARCHAR2_TABLE,
    PERIODO_INFORMADO            DBMS_SQL.VARCHAR2_TABLE,
    FECHA_COMPILACION            DBMS_SQL.VARCHAR2_TABLE,
    ID_ENTIDAD                   DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_CLIENTE               DBMS_SQL.VARCHAR2_TABLE,
    TIPO_DOCUMENTO               DBMS_SQL.VARCHAR2_TABLE,
    NRO_DOCUMENTO                DBMS_SQL.VARCHAR2_TABLE,
    CLASIFICACION                DBMS_SQL.VARCHAR2_TABLE,
    TIN                          DBMS_SQL.VARCHAR2_TABLE,
    NOMBRE                       DBMS_SQL.VARCHAR2_TABLE,
    APELLIDO                     DBMS_SQL.VARCHAR2_TABLE,
    DIRECCION                    DBMS_SQL.VARCHAR2_TABLE,
    PAIS_RESIDENCIA              DBMS_SQL.VARCHAR2_TABLE,
    CIUDAD                       DBMS_SQL.VARCHAR2_TABLE,
    PROVINCIA                    DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_POSTAL                DBMS_SQL.VARCHAR2_TABLE,
    REFERENCIA_DIRECCION         DBMS_SQL.VARCHAR2_TABLE,
    FECHA_NACIMIENTO             DBMS_SQL.VARCHAR2_TABLE,
    GRUPO_REPORTE                DBMS_SQL.VARCHAR2_TABLE,
    ID_DOC_SPEC                  DBMS_SQL.VARCHAR2_TABLE,
    ID_REPORTE                   DBMS_SQL.VARCHAR2_TABLE,
    NRO_CUENTA                   DBMS_SQL.VARCHAR2_TABLE,
    TITULAR_CUENTA               DBMS_SQL.VARCHAR2_TABLE,
    PROPIETARIOS_SUSTANCIALES    DBMS_SQL.VARCHAR2_TABLE,
    SALDO_CUENTA                 DBMS_SQL.VARCHAR2_TABLE,
    SALDO_MONEDA                 DBMS_SQL.VARCHAR2_TABLE,
    ENTIDAD_CONTRATO             DBMS_SQL.VARCHAR2_TABLE,
    VALOR_NOMINAL                DBMS_SQL.VARCHAR2_TABLE,
    VALOR_NOMINAL_MONEDA         DBMS_SQL.VARCHAR2_TABLE,
    VALOR_MERCADO                DBMS_SQL.VARCHAR2_TABLE,
    VALOR_MERCADO_MONEDA         DBMS_SQL.VARCHAR2_TABLE,
    TIPO_FONDO                   DBMS_SQL.VARCHAR2_TABLE,
    MONTO_501                    DBMS_SQL.VARCHAR2_TABLE,
    MONTO_502                    DBMS_SQL.VARCHAR2_TABLE,
    MONTO_503                    DBMS_SQL.VARCHAR2_TABLE,
    MONTO_504                    DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_501                   DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_502                   DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_503                   DBMS_SQL.VARCHAR2_TABLE,
    MONEDA_504                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_501                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_502                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_503                   DBMS_SQL.VARCHAR2_TABLE,
    ORIGEN_504                   DBMS_SQL.VARCHAR2_TABLE,
    CODIGO_CUSTODIO              DBMS_SQL.VARCHAR2_TABLE,
    ADMINISTRACION_MERCADO       DBMS_SQL.VARCHAR2_TABLE,
    PERIODO_ID                   DBMS_SQL.VARCHAR2_TABLE,
    LINEA                        DBMS_SQL.VARCHAR2_TABLE,
    ESTADO                       DBMS_SQL.VARCHAR2_TABLE,
    ESTADO_PROCESO               DBMS_SQL.VARCHAR2_TABLE,
    MENSAJE                      DBMS_SQL.VARCHAR2_TABLE
  );

  PROCEDURE SP_CARGAR_FATCA(USUARIO VARCHAR2, ID_PROCESO NUMBER, FILAS_LEIDAS OUT NUMBER, FILAS_ESCRITAS OUT NUMBER, ESTADO OUT VARCHAR2, DESCRIPCION OUT VARCHAR2);
  PROCEDURE SP_INSERTAR_PAYMENT(P_ID_PAYMENT NUMBER, P_SALDO VARCHAR2, P_MONEDA VARCHAR2, P_ORIGEN VARCHAR2, P_USUARIO VARCHAR2, P_ACCOUNT_REPORT_ID NUMBER, P_PARAMETRO PARAMETRO%ROWTYPE, P_ID_PERIODO NUMBER);
  PROCEDURE SP_INSERTAR_SUSTANCIAL(P_USUARIO VARCHAR2, P_ACCOUNT_REPORT_ID NUMBER, P_CODIGOCLIENTE VARCHAR2, P_ID_PERIODO NUMBER);
  PROCEDURE SP_INSERTAR_ACCOUNT(P_CUENTA T_CUENTA, K NUMBER, P_FATCA_OECD_ID NUMBER, P_ID_PERIODO NUMBER, USUARIO VARCHAR2, P_ID_PROCESO NUMBER, P_REPORTING_GROUP_ID NUMBER, P_CORR_MESSAGE_REF_ID VARCHAR2, P_FLAG_TEST VARCHAR2, P_SUSTANCIAL NUMBER);
  FUNCTION SF_VERIFICAR_ACCOUNT(P_CUENTA T_CUENTA, K NUMBER, P_ID_PERIODO NUMBER, P_USUARIO VARCHAR2, P_ID_PROCESO NUMBER) RETURN NUMBER;
  FUNCTION SF_OBTENER_DOCREFID(P_NRO_CUENTA VARCHAR2, P_CODIGO_CLIENTE VARCHAR2, P_TIPO_FONDO VARCHAR2, P_PROCESO VARCHAR2, P_GIIN_ORGANISATION VARCHAR2) RETURN VARCHAR2;
  FUNCTION SF_OBTENER_CORREFID(P_NRO_CUENTA VARCHAR2, P_PROCESO VARCHAR2, P_FATCA_OECD_ID NUMBER, P_TIN VARCHAR2) RETURN VARCHAR2;
END PKG_PROCESOS_SALIDA;
/

spool off
