spool 11_grants.log

GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.FATCA            TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.ACCIONISTAS      TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.ACCOUNT_REPORT   TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.CUENTAS          TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.FATCA_OECD       TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.INTERMEDIARY     TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.LOG              TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.ORGANISATION     TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.PARAMETRO        TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.PAYMENT          TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.PERIODO          TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.PERSON           TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.POOL_REPORT      TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.REPORTING_FI     TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.REPORTING_GROUP  TO APP_FATCA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FATCA.SUSTANTIAL_OWNER TO APP_FATCA;

GRANT SELECT ON FATCA.SQ_FATCA            TO APP_FATCA; 
GRANT SELECT ON FATCA.SQ_ACCIONISTAS      TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_ACCOUNT_REPORT   TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_CUENTAS          TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_FATCA_OECD       TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_INTERMEDIARY     TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_LOG              TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_ORGANISATION     TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_PARAMETRO        TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_PAYMENT          TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_PERIODO          TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_PERSON           TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_POOL_REPORT      TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_REPORTING_FI     TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_REPORTING_GROUP  TO APP_FATCA;
GRANT SELECT ON FATCA.SQ_SUSTANTIAL_OWNER TO APP_FATCA;

GRANT SELECT ON FATCA.VW_PERSONA          TO APP_FATCA;
GRANT SELECT ON FATCA.QRTZ_VW_TRIGGERS    TO APP_FATCA;

GRANT EXECUTE ON FATCA.PKG_PROCESOS_ENTRADA TO APP_FATCA;
GRANT EXECUTE ON FATCA.PKG_PROCESOS_SALIDA  TO APP_FATCA;
GRANT EXECUTE ON FATCA.PKG_UTIL             TO APP_FATCA;
GRANT EXECUTE ON FATCA.PKG_CONSULTAS        TO APP_FATCA;

spool off
